Feature/add top series correlation
baobabsoluciones/mango pull request #105
Opened 2023-12-11 13:30 UTC by montsemunoz

2023-12-12 09:00 UTC, ggsdc commented on mango/tests/data_module/test_correlation_ts.py
> +    def setUpClass(cls) -> None:
Why use `setUpClass` instead of `setUp`?

2023-12-12 09:00 UTC, ggsdc commented on requirements.txt
> +tabulate
Should we also change the `pyproject.toml`?

2023-12-12 11:08 UTC, gvalleg commented on mango/data/__init__.py
> +from .series_correlations import get_corr_matrix
I think this kind of functions would be better in the processing module, in the processing_time _series.py script.
@AntonioGonzalezSuarez @ggsdc What do you think?

2023-12-12 14:42 UTC, gvalleg requested changes
Change the functions to processing module

2023-12-13 08:39 UTC, AntonioGonzalezSuarez requested changes

2023-12-13 08:39 UTC, AntonioGonzalezSuarez commented on mango/processing/processing_time_series.py
> +) -> Dict[str]:
Dict needs two argument. First is the type of the key and second the type of the value. For this case should be as follows:

```python
Dict[str,Dict[str,float]]
```

2023-12-20 16:45 UTC, ggsdc approved these changes

2023-12-20 17:54 UTC, merged