fix for reading variables from xlsx file
baobabsoluciones/mango pull request #142
Opened 2024-10-17 13:47 UTC by bwronska

The function instance_from_excel returns the error while reading model variables from excel file. The following commit should fix that issue

2024-10-18 13:09 UTC, ggsdc commented
Can we add a test to this function as it seems that it is not covered by tests?

2024-10-21 10:46 UTC, ggsdc requested changes

2024-10-21 10:46 UTC, ggsdc commented on mango/tests/processing_module/test_file_functions.py
> +    write_excel_light, load_str_iterable,
This has not been black formatted

2024-10-21 12:50 UTC, gvalleg approved these changes

2024-10-21 17:15 UTC, ggsdc approved these changes

2024-10-22 10:18 UTC, merged