Feature/modelling mstllgbm
baobabsoluciones/mango pull request #145
Opened 2024-10-29 12:06 UTC by gvalleg

Incorporate changes from modellingMSTLLGBM into custom_folds

2024-10-29 12:09 UTC, antoniogonzalezsuarez commented
The scripts are fine but I don't know if the repo is the place to be. Please do not remove yet

2024-10-29 12:09 UTC, antoniogonzalezsuarez commented on mango_base/mango/dashboards/__init__.py
We will check this in future merge but it seems like should not be here

2024-10-29 12:24 UTC, gvalleg reviewed
A lot of changes and files that must not be there.

2024-10-29 12:24 UTC, gvalleg commented on mango_base/mango/dashboards/__init__.py
> +# from .file_explorer_app import FileExplorerApp
Why?

2024-10-29 12:24 UTC, gvalleg commented on mango_base/mango/dashboards/time_series_app.py
> +    logo_path = r"https://www.multiserviciosaeroportuarios.com/wp-content/uploads/2024/03/cropped-Logo-transparente-blanco-Multiservicios-Aeroportuarios-Maero-1-192x192.png"
This should not be here.

2024-10-29 12:24 UTC, gvalleg commented on mango_base/mango/dashboards/time_series_app.py
> +import pandas as pd
Review if this script .py must be here or in the time-series-dashboard branch.
@antoniogonzalezsuarez

2024-10-29 12:24 UTC, gvalleg commented on mango_base/mango/dashboards/time_series_utils/constants.py
> +# Constants for time aggregation
Review if this script .py must be here or in the time-series-dashboard branch.
@antoniogonzalezsuarez

2024-10-29 12:24 UTC, gvalleg commented on mango_base/mango/dashboards/time_series_utils/data_loader.py
> +import streamlit as st
Review if this script .py must be here or in the time-series-dashboard branch.
@antoniogonzalezsuarez

2024-10-29 12:24 UTC, gvalleg commented on mango_base/mango/dashboards/time_series_utils/data_processing.py
> +from mango_time_series.mango.utils.processing import aggregate_to_input
Review if this script .py must be here or in the time-series-dashboard branch.
@antoniogonzalezsuarez

2024-10-29 12:24 UTC, gvalleg commented on mango_base/mango/dashboards/time_series_utils/file_uploader.py
> +import streamlit as st
Review if this script .py must be here or in the time-series-dashboard branch.
@antoniogonzalezsuarez

2024-10-29 12:24 UTC, gvalleg commented on mango_base/mango/dashboards/time_series_utils/ui_components.py
> +import pandas as pd
Review if this script .py must be here or in the time-series-dashboard branch.
@antoniogonzalezsuarez

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/mango/tests/data/calendar_pivot_keep_com.csv
> +date,country_code,community_name,80 Aniversario del primer Gobierno Vasco,Ano nuevo,Asuncion de la Virgen,Corpus Christi,Dia Nacional de Galicia,Dia de Andalucia,Dia de Asturias,Dia de Canarias,Dia d
This should not be here.

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/mango/tests/data/calendar_pivot_keep_com_distances.csv
This should not be here.

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/mango/tests/data/calendar_pivot_keep_com.csv
This should not be here.

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/mango/tests/data/calendar_com_pivot.csv
This should not be here.

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/mango/tests/data/calendar_com.csv
This should not be here.

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/mango/tests/data/calendar.csv
This should not be here.

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/mango/utils/processing.py
> +        date_end="2024-10-01",
This should be in SERIES_CONF?

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/script_MSTL.py
> +    r"G:\Unidades compartidas\clece_pmr_202207\proyecto\desarrollo\datos\time_series_synthetic_interpolate.xlsx"
This should not be here.

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/script_MSTL.py
> +# df["aeropuerto"] = "BCN"
This should not be here.

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/script_TBATS.py
I think that this file is a project file that we need to remove

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/script_MSTL.py
I think that this file is a project file that we need to remove

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/script_aLGBM.py
I think that this file is a project file that we need to remove.

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/script_nLGBM.py
I think that this file is a project file that we need to remove

2024-10-29 12:24 UTC, gvalleg commented on mango_time_series/script_nbeats.py
I think that this file is a project file that we need to remove

2024-10-30 13:34 UTC, ggsdc requested changes
A lot of changes neede here, and need to update with curent version of develop branch

2024-10-30 13:34 UTC, ggsdc commented on mango_time_series/mango/utils/__init__.py
> +
This has to be changed to `from mango_time_series.utils.COSNT import ...`

2024-11-06 10:12 UTC, merged