fix left_join and add test
baobabsoluciones/mango pull request #46
Opened 2023-05-31 13:15 UTC by hugolarzabal

2023-10-13 11:32 UTC, ggsdc approved these changes

2023-10-13 11:33 UTC, ggsdc commented
@gvalleg @AntonioGonzalezSuarez @dlopbar @l-prr could any of you review this PR as well?

2023-10-16 06:54 UTC, AntonioGonzalezSuarez requested changes

2023-10-16 06:54 UTC, AntonioGonzalezSuarez commented on mango/table/pytups_table.py
>          :param empty: values to give to empty cells created by the join.
Outdated docstring

2023-10-16 06:54 UTC, AntonioGonzalezSuarez commented on mango/table/pytups_tools.py
>      :param empty: values to give to empty cells created by the join.
Outdated docstring

2023-10-16 06:54 UTC, AntonioGonzalezSuarez commented on mango/table/pytups_tools.py
>      :param empty: values to give to empty cells created by the join.
Outdated doctring

2023-10-16 06:54 UTC, AntonioGonzalezSuarez commented on mango/table/pytups_tools.py
>      :param empty: values to give to empty cells created by the join.
Outdated docstring

2023-10-16 06:54 UTC, AntonioGonzalezSuarez commented on mango/table/pytups_tools.py
>      :param empty: values to give to empty cells created by the join.
Outdated docstring

2023-10-16 06:54 UTC, AntonioGonzalezSuarez commented on mango/table/pytups_table.py
>          """
Missing docstring

2023-10-16 06:54 UTC, AntonioGonzalezSuarez commented on mango/table/pytups_table.py
>          """
Missing docstring

2023-10-16 06:54 UTC, AntonioGonzalezSuarez commented on mango/table/pytups_table.py
>          """
Missing docstring

2023-10-16 06:54 UTC, AntonioGonzalezSuarez commented on mango/table/pytups_table.py
>          """
Missing docstring

2023-10-16 10:24 UTC, AntonioGonzalezSuarez approved these changes

2023-10-16 10:27 UTC, AntonioGonzalezSuarez approved these changes
Approved

2023-10-16 10:28 UTC, ggsdc approved these changes

2023-10-16 10:31 UTC, AntonioGonzalezSuarez approved these changes

2023-10-16 13:45 UTC, merged