Commented some tests out
baobabsoluciones/mango pull request #91
Opened 2023-11-22 16:10 UTC by ggsdc

2023-11-22 16:27 UTC, AntonioGonzalezSuarez commented
When running test, variables.xlsx gets modified or at least that is what git detects. Any idea why?

2023-11-22 17:02 UTC, hugolarzabal requested changes

2023-11-22 17:02 UTC, hugolarzabal commented on mango/tests/table_module/test_tools.py
> +    #     self.assertEqual(result, expected)
you could comment only the assertWarns and leave the rest of the test

2023-11-22 17:06 UTC, hugolarzabal commented
> ###
> [Nov 22, 2023](#issuecomment-1823091616)

Some of the function write the file variables.xlsx. I think they overwrite it and even if there is the same data, Excel consider it has changed.
I think the tests should be changed to write (and delete) a file with another name. @bwronska

2023-11-23 09:54 UTC, gvalleg approved these changes

2023-11-23 09:58 UTC, AntonioGonzalezSuarez approved these changes

2023-11-23 10:02 UTC, merged