Feature/dashboard add UUID
baobabsoluciones/mango pull request #93
Opened 2023-11-24 11:28 UTC by montsemunoz

Add uuid in key

2023-11-24 11:58 UTC, gvalleg commented on mango/dashboards/file_explorer_app.py
> +                            key=f"{key_tab}_{uuid.uuid4()},
This line solves the rendering problem but prevents the saving of files. I'm going to check this part to get everything right.

2023-11-24 11:59 UTC, gvalleg requested changes
This problem also needs to be solved for JSON files and to save changes to the files properly.

2023-11-24 13:30 UTC, gvalleg approved these changes

2023-11-27 08:58 UTC, ggsdc approved these changes

2023-11-27 09:03 UTC, merged